sudo: required
services:
  - docker

before_install:
  - docker build -t byz96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true byz96/docker-react npm run test 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-585093177798"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_key_id: $AWS_SECRET_KEY

